[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
privy_pstree = "DY2QrWnr4tKX9tMSeYLMajFjTaa33uqkzbkBwHfbNgqS"
privy_verifier = "BuiA3HBdZhbsHZDGGVvVeudVGxeMjg2n5uozTWEePTzN"

[programs.localnet]
privy_pstree = "3pD8r4QpTbvRtUeQvqrJ7oE8DDHXkB1udmnopPzDrtNg"
privy_verifier = "VfyP111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/privy-verifier", "programs/privy-pstree"]
types = "target/types"

[scripts]
test = "cargo test-sbf -- --nocapture"

[hooks]
