[features]
seeds = false
skip-lint = false

[programs.localnet]
privy_verifier = "VfyP111111111111111111111111111111111111111"
privy_pstree = "3pD8r4QpTbvRtUeQvqrJ7oE8DDHXkB1udmnopPzDrtNg"

[programs.devnet]
privy_verifier = "VfyP111111111111111111111111111111111111111"
privy_pstree = "3pD8r4QpTbvRtUeQvqrJ7oE8DDHXkB1udmnopPzDrtNg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-sbf -- --nocapture"

[workspace]
types = "target/types"
members = [
    "programs/privy-verifier",
    "programs/privy-pstree",
]
